# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    filter_sets:
        squarePortrait:
            quality: 75
            filters:
                thumbnail:
                    size: [1162,1164]
                    mode: outbound

        recPortrait:
            quality: 75
            filters:
                thumbnail:
                    size: [280,411]
                    mode: outbound

        paysage:
            quality: 75
            filters:
                thumbnail:
                    size: [961,450]
                    mode: outbound
