# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    filter_sets:
        portrait:
            quality: 75
            filters:
                thumbnail:
                    size: [260,260]
                    mode: outbound

        smallPortrait:
            quality: 75
            filters:
                thumbnail:
                    size: [200,200]
                    mode: outbound

        smallPaysage:
            quality: 75
            filters:
                thumbnail:
                    size: [150,100]
                    mode: outbound

        medium:
            quality: 75
            filters:
                thumbnail:
                    size: [961,450]
                    mode: outbound
