vich_uploader:
    db_driver: orm

    mappings:
        home_image:
            uri_prefix: /images/home
            upload_destination: '%kernel.project_dir%/public/images/home'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        about_image:
            uri_prefix: /images/about
            upload_destination: '%kernel.project_dir%/public/images/about'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        projet_image:
            uri_prefix: /images/projet
            upload_destination: '%kernel.project_dir%/public/images/projet'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        formation_image:
            uri_prefix: /images/formation
            upload_destination: '%kernel.project_dir%/public/images/formation'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        skill_image:
            uri_prefix: /images/skill
            upload_destination: '%kernel.project_dir%/public/images/skill'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        experience_image:
            uri_prefix: /images/experience
            upload_destination: '%kernel.project_dir%/public/images/experience'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
